version: '3.5'
services:

  node1:
    image: blokaly/xpindy-node1
    container_name: indy-node1
    networks:
      indy-demo-network:
        ipv4_address: 172.18.0.2
    restart: unless-stopped

  node2:
    image: blokaly/xpindy-node2
    container_name: indy-node2
    networks:
      indy-demo-network:
        ipv4_address: 172.18.0.3
    restart: unless-stopped

  nodejs-demo:
    image: blokaly/indy-nodejs-demo
    container_name: indy-nodejs-demo
    stdin_open: true
    tty: true
    networks:
      indy-demo-network:
        ipv4_address: 172.18.0.4
    restart: unless-stopped

networks:
  indy-demo-network:
    name: indy-demo-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
      driver: default
